jobs:
  javadoc:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Javadoc
      run: ant clean javadoc -buildfile build.xml
    strategy:
      matrix:
        java:
        - '11'
        os:
        - ubuntu-latest
  rat:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Run Apache Rat
      run: ant clean run-rat -buildfile build.xml
    - continue-on-error: true
      name: Cache unknown licenses
      run: echo "UNKNOWN_LICENSES=$(sed -n 18p /home/runner/work/nutch/nutch/build/apache-rat-report.txt)"
        >> $GITHUB_ENV
    - continue-on-error: true
      name: Versions
      run: 'echo $UNKNOWN_LICENSES

        '
    - continue-on-error: true
      if: ${{ env.UNKNOWN_LICENSES != '0 Unknown Licenses' }}
      name: Fail if any unknown licenses
      run: exit 1
    strategy:
      matrix:
        java:
        - '11'
        os:
        - ubuntu-latest
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Test
      run: ant clean test -buildfile build.xml
    strategy:
      matrix:
        java:
        - '11'
        os:
        - ubuntu-latest
        - macos-latest
name: master pull request ci
on:
  repository_dispatch:
    types: trigger-ga___master-build.yml
